export const CURRENT_USER_STARTED = 'CURRENT_USER_STARTED'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAILURE = 'CURRENT_USER_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_ALL_USERS_STARTED = 'GET_ALL_USERS_STARTED'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE'
