export const CURRENT_USER_STARTED = 'CURRENT_USER_STARTED'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAILURE = 'CURRENT_USER_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
